apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-ui
  template:
    metadata:
      labels:
        app: main-ui
    spec:
      initContainers:
      - name: init-backend-api-check
        image: mcr.microsoft.com/azurelinux/busybox:1.36
        command:
          - sh
          - -c
          - |
            until nc -z -v -w30 backend-api.contoso-hypermarket.svc.cluster.local 5002 && \
                  nc -z -v -w30 footfall-ai-api.contoso-hypermarket.svc.cluster.local 5000 && \
                  nc -z -v -w30 cerebral-api-service.contoso-hypermarket.svc.cluster.local 5003; do
              echo "Waiting for the backend-api, footfall-ai-api, and cerebral-api-service to start"
              sleep 5
            done
      containers:
      - name: main-ui
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: REACT_APP_FOOTFALL_API
          value: "http://footfall-ai-api.contoso-hypermarket.svc.cluster.local:5000"
        - name: REACT_APP_CEREBRAL_API_URL
          value: "http://cerebral-api-service.contoso-hypermarket.svc.cluster.local:5003/Cerebral/api/process_question"
        - name: REACT_APP_STORE_API_URL
          value: "http://backend-api.contoso-hypermarket.svc.cluster.local:5002"
        - name: REACT_APP_CEREBRAL_WS_URL
          value: "http://cerebral-api-service.contoso-hypermarket.svc.cluster.local:5003"