apiVersion: v1
kind: Service
metadata:
  name: main-ui
spec:
  selector:
    app: main-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
