apiVersion: v1
kind: Service
metadata:
  name: footfall-ai-api
spec:
  selector:
    app: footfall-ai-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}