# Use the official Python image
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

# Install Tini and Supervisor
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    supervisor \
    libmagic1 \
    git-lfs \
    unixodbc \
    unixodbc-dev \
    freetds-dev \
    freetds-bin \
    tdsodbc \
    wget \  
    && rm -rf /var/lib/apt/lists/*

# Create the application directory
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    # Install remaining dependencies
    pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app

ENV AZURE_OPENAI_API_KEY=<your_azure_openai_api_key> \
    CHATGPT_MODEL=gpt-35-turbo \
    AZURE_OPENAI_ENDPOINT=<your_azure_openai_endpoint> \
    OPENAI_API_VERSION=2024-03-01-preview \
    # Environment variables for InfluxDB
    INFLUXDB_URL=http://influxdb.cerebral.svc.cluster.local:8086 \
    INFLUXDB_BUCKET=cerebral \
    INFLUXDB_TOKEN=secret-token \
    INFLUXDB_ORG=InfluxData \
    # Environment variables for SQL
    SQL_DATABASE=RetailDB \
    SQL_SERVER=10.0.0.4 \
    SQL_USERNAME=SA \
    SQL_PASSWORD=ArcPassword123!!
    #RAG on the Edge
    # Environment variables
    ENV PYTHONUNBUFFERED=1
    # chroma-db-service
    ENV CHROMA_HOST=10.0.0.4  
    ENV CHROMA_PORT=8040
    ENV CHROMA_COLLECTION=documents
    ENV DOCUMENTS_PATH=docs
    ENV MODEL_PATH=cuda/cuda-int4-rtn-block-32 
    ENV USE_LOCAL_LLM=True
    ENV PORT=5003
    ENV STORE_ID=SEA

# Copy the Supervisor configuration
COPY supervisor.conf /etc/supervisor/conf.d/supervisord.conf

# Expose the ports that the applications will use
EXPOSE 5003

CMD ["python", "app.py"]
