apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cerebral-service-monitor
  labels:
    release: prometheus  
spec:
  endpoints:
  - port: cerebral-metrics # Make sure this matches the port name of your service
    interval: 30s
    path: /metrics
  selector:
    matchLabels:
      app: cerebral-simulator-service # Make sure this matches the label of your service