apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
  namespace: azure-iot-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decode
  template:
    metadata:
      labels:
        app: decode
    spec:
      containers:
      - name: decode
        image: agoraarmbladev.azurecr.io/decode-svc:1.6
        ports:
        - containerPort: 80
        env:
        - name: rtsp_url
          value: "rtsp://10.211.55.5:8554/stream"
        - name: save_path
          value: "frames"

---
apiVersion: v1
kind: Service
metadata:
  name: decode
  namespace: azure-iot-operations
spec:
  type: LoadBalancer 
  selector:
    app: decode
  ports:
  - name: rtsp
    port: 80
    protocol: TCP
    targetPort: 80
