apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
  namespace: azure-iot-operations
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create-credentials
          image: influxdb:latest
          command:
            - influx
          args:
            - setup
            - --host
            - http://10.211.55.5:8086
            - --bucket
            - manufacturing
            - --org
            - InfluxData
            - --password
            - s1$mpl3p4ssw0rd
            - --username
            - admin
            - --token
            - secret-token
            - --force
