apiVersion: v1
kind: ConfigMap
metadata:
  name: genie-config
  namespace: contoso-hypermarket
data:
  FLASK_APP: "app.py"
  FLASK_ENV: "development"
  DATABASE_HOST: "mssql"
  DATABASE_NAME: "RetailDB"
  DATABASE_USER: "sa"
  DATABASE_PASSWORD: "ArcPassword123!!"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  namespace: contoso-hypermarket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: contoso-hypermarket
spec:
  selector:
    matchLabels:
      app: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: genie-config
              key: DATABASE_PASSWORD
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssql-storage
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: mssql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: contoso-hypermarket
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: genie-api
  namespace: contoso-hypermarket
spec:
  selector:
    matchLabels:
      app: genie-api
  replicas: 1
  template:
    metadata:
      labels:
        app: genie-api
    spec:
      containers:
      - name: genie-api
        image: agacr5bbaf.azurecr.io/genie-api:latest
        ports:
        - containerPort: 5004
        envFrom:
        - configMapRef:
            name: genie-config

---

apiVersion: v1
kind: Service
metadata:
  name: genie-api
  namespace: contoso-hypermarket
spec:
  selector:
    app: genie-api
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: LoadBalancer