apiVersion: v1
kind: Service
metadata:
  name: backend-api
spec:
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5002
  type: {{ .Values.service.type }}