apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopper-experience-api
  namespace: contoso-hypermarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopper-experience-api
  template:
    metadata:
      labels:
        app: shopper-experience-api
    spec:
      initContainers:
      - name: init-download-model
        image: mcr.microsoft.com/cbl-mariner/base/core:2.0
        command: 
          - sh
          - -c
          - |
            tdnf update -y
            tdnf install wget -y
            wget -O /tmp/models/person-detection-retail-0013.xml https://download.microsoft.com/download/d68ed0fa-655f-4e7a-b2fc-a44224a80d8b/person-detection-retail-0013.bin
            wget -O /tmp/models/person-detection-retail-0013.xml https://download.microsoft.com/download/d68ed0fa-655f-4e7a-b2fc-a44224a80d8b/person-detection-retail-0013.xml
            wget -O /tmp/models/person-detection-retail-0013.xml https://download.microsoft.com/download/d68ed0fa-655f-4e7a-b2fc-a44224a80d8b/person-reidentification-retail-0287.bin
            wget -O /tmp/models/person-detection-retail-0013.xml https://download.microsoft.com/download/d68ed0fa-655f-4e7a-b2fc-a44224a80d8b/person-reidentification-retail-0287.xml
        volumeMounts:
        - name: models-volume
          mountPath: /tmp/models
      containers:
      - name: shopper-experience-api
        image: agacrd2f52.azurecr.io/shopper-experience-api:latest
        ports:
        - containerPort: 5001
        env:
        - name: MODEL_PATH
          value: "/tmp/models/"
        - name: RTSP_URL
          value: "rtsp://rtsp-stream:8554/stream"
        - name: FLASK_PORT
          value: "5001"
        volumeMounts:
        - mountPath: /tmp/models
          name: models-volume
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: model-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: shopper-experience-api
  namespace: contoso-hypermarket
spec:
  selector:
    app: shopper-experience-api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
