broker:
  mqttBroker:
    image:
      repository: mcr.microsoft.com/jumpstart/agora/freezer_monitoring_mqtt_broker
      tag: 1.0.0
    imagePullPolicy: Always
  ports:
    - name: http
      port: 1883
      targetPort: 1883
  replicas: 1
  type: LoadBalancer
kubernetesClusterDomain: cluster.local
simulator:
  mqttSimulator:
    image:
      repository: mcr.microsoft.com/jumpstart/agora/freezer_monitoring_mqtt_simulator
      tag: 1.0.0
    imagePullPolicy: Always
  replicas: 1
mqtt2prom:
  mqtt2prom:
    image:
      repository: ghcr.io/hikhvar/mqtt2prometheus
      tag: latest
    imagePullPolicy: Always
  ports:
    - name: mqtt2prom-agora-metrics
      port: 9641
      targetPort: 9641
  replicas: 1
  type: LoadBalancer
