apiVersion: apps/v1
kind: Deployment
metadata:
  name: genie-api-deployment
  namespace: genie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genie-api
  template:
    metadata:
      labels:
        app: genie-api
    spec:
      containers:
      - name: genie-api
        image: agoraarmbladev.azurecr.io/genie-api:0.1
        ports:
        - containerPort: 5003
        env:
        - name: AZURE_OPENAI_API_KEY
          value: "your_azure_openai_api_key"
        - name: CHATGPT_MODEL
          value: "gpt-35-turbo"
        - name: AZURE_OPENAI_ENDPOINT
          value: "your_azure_openai_endpoint"
        - name: OPENAI_API_VERSION
          value: "2024-03-01-preview"
        - name: INFLUXDB_URL
          value: "http://influxdb.genie.svc.cluster.local:8086"
        - name: INFLUXDB_BUCKET
          value: "genie"
        - name: INFLUXDB_TOKEN
          value: "secret-token"
        - name: INFLUXDB_ORG
          value: "InfluxData"
        - name: REDIS_URL
          value: "redis://redis-service.genie.svc.cluster.local:6379"
        - name: SQL_DATABASENAME
          value: "ReatilDB"
        - name: SQL_SERVER
          value: "10.0.0.4"
        - name: SQL_USERNAME
          value: "SA"
        - name: SQL_PASSWORD
          value: "ArcPassword123!!"

---
apiVersion: v1
kind: Service
metadata:
  name: genie-api-service
  namespace: genie
spec:
  type: LoadBalancer
  selector:
    app: genie-api
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003