apiVersion: v1
kind: ConfigMap
metadata:
  name: genie-simulator-config
  namespace: contoso-hypermarket
data:
  INFLUXDB_URL: "http://influxdb.contoso-hypermarket.svc.cluster.local:8086"
  INFLUXDB_TOKEN: "secret-token"
  INFLUXDB_ORG: "InfluxData"
  INFLUXDB_BUCKET: "hypermarket"
  MQTT_BROKER: "localhost"
  MQTT_PORT: "1883"
  MQTT_TOPIC: "iot/devices"
  REFRIGERATOR_COUNT: "3"
  SCALE_COUNT: "2"
  POS_COUNT: "5"
  SMARTSHELF_COUNT: "3"
  HVAC_COUNT: "3"
  LIGHTINGSYSTEM_COUNT: "3"
  AUTOMATEDCHECKOUT_COUNT: "3"
  EVENTHUB_CONNECTION_STRING: "https://aiohubns021ef.servicebus.windows.net:443/"
  ORDERS_EVENTHUB_NAME: ORDERS
  INVENTORY_EVENTHUB_NAME: INVENTORY
  HISTORICAL_DATA_DAYS: "1"
  ORDER_FREQUENCY: "10"
  PRODUCTS_FILE: "products.json"
  UI_API_URL: "http://backend-api.contoso-hypermarket.svc.cluster.local:5002"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: genie-simulator
  namespace: contoso-hypermarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genie-simulator
  template:
    metadata:
      labels:
        app: genie-simulator
    spec:
      containers:
      - name: genie-simulator
        image: agacrd2f52.azurecr.io/genie-simulator:latest
        envFrom: 
        - configMapRef:
            name: genie-simulator-config

---

apiVersion: v1
kind: Service
metadata:
  name: genie-simulator-service
  namespace: contoso-hypermarket
spec:
  type: LoadBalancer
  selector:
    app: genie-simulator
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001