apiVersion: v1
kind: ConfigMap
metadata:
  name: genie-simulator-config
  namespace: contoso-hypermarket
data:
  INFLUXDB_URL: "http://influxdb.contoso-hypermarket.svc.cluster.local:8086"
  INFLUXDB_TOKEN: "secret-token"
  INFLUXDB_ORG: "InfluxData"
  INFLUXDB_BUCKET: "hypermarket"
  MQTT_BROKER: "localhost"
  MQTT_PORT: "1883"
  MQTT_TOPIC: "iot/devices"
  REFRIGERATOR_COUNT: "3"
  SCALE_COUNT: "2"
  POS_COUNT: "5"
  SMARTSHELF_COUNT: "3"
  HVAC_COUNT: "3"
  LIGHTINGSYSTEM_COUNT: "3"
  AUTOMATEDCHECKOUT_COUNT: "3"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: genie-simulator
  namespace: contoso-hypermarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genie-simulator
  template:
    metadata:
      labels:
        app: genie-simulator
    spec:
      containers:
      - name: genie-simulator
        image: agacrd2f52.azurecr.io/genie-simulator:latest
        envFrom: 
        - configMapRef:
            name: genie-simulator-config

---

apiVersion: v1
kind: Service
metadata:
  name: genie-simulator-service
  namespace: contoso-hypermarket
spec:
  type: LoadBalancer
  selector:
    app: genie-simulator
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001