apiVersion: apps/v1
kind: Deployment
metadata:
  name: genie-simulator
  namespace: contoso-hypermarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genie-simulator
  template:
    metadata:
      labels:
        app: genie-simulator
    spec:
      containers:
      - name: genie-simulator
        image: agacrd2f52.azurecr.io/genie-simulator:latest
        ports:
        - containerPort: 5000
        env:
        - name: INFLUXDB_URL
          value: "http://influxdb.contoso-hypermarket.svc.cluster.local:8086"
        - name: INFLUXDB_TOKEN
          value: "secret-token"
        - name: INFLUXDB_ORG
          value: "InfluxData"
        - name: INFLUXDB_BUCKET
          value: "manufacturing"
        - name: VERBOSE
          value: "true"
