apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:11.0-base
      command: ["sleep", "infinity"]
      resources:
        limits:
          nvidia.com/gpu: 1
