apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contoso-hypermarket
  namespace: contoso-hypermarket
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: contoso-hypermarket
  chart:
    spec:
      chart: ./agora/contoso_hypermarket/charts/contoso-hypermarket