services:
  main_ui:
    build:
      context: ../main_ui/src
      dockerfile: Dockerfile
    container_name: main_ui_container
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_FOOTFALL_API=http://footfall_ai_api_container:5000
      - REACT_APP_INTRUSION_API=http://shopper_insights_api:5001
      - REACT_APP_CEREBRAL_API_URL=http://cerebral_api:5002
