services:
  store_api:
    build:
      context: ../main_ui_backend_api/src  # This should point to the folder containing the Dockerfile and requirements.txt
      dockerfile: Dockerfile
    container_name: store_api_container
    ports:
      - "5002:5002"  # Adjusting to expose port 5001 as mapped in the Dockerfile
    environment:
      - DATABASE_HOST=backend_db
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=contoso
      - DATABASE_USER=postgres
      - MQTT_BROKER=test.mosquitto.org
      - MQTT_PORT=1883
      - MQTT_TOPIC=Store/Cameras/PeopleCount
      - FOOTFALL_API=http://footfall-ai-api:5000/status
      - SI_API=http://shopper-insights-api:5001/status
    entrypoint: ["/bin/bash", "init-db.sh"]