services:
  backend_db:
    image: mcr.microsoft.com/cbl-mariner/base/postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contoso
    ports:
      - "5432:5432"
    volumes: 
      - /mnt/C/Users/dakir/postgresql/data:/var/postgresql/data