services:
  main_ui:
    build:
      context: ../main_ui/src
      dockerfile: Dockerfile
    container_name: main_ui_container
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_FOOTFALL_VIDEO_URL=http://footfall_ai_api_container:5000/video_feed?x=50&y=20&w=540&h=320&source=rtsp://rtsp_stream_container:8554/stream
      - REACT_APP_INTRUSION_VIDEO_URL=http://shopper_insights_api:5001/video_feed?x=50&y=20&w=540&h=320&source=rtsp://rtsp_stream_container:8554/stream
      - REACT_APP_GENIE_API_URL=http://genie_api:5002
