apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-stream-aisle
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rtsp-stream-aisle
  template:
    metadata:
      labels:
        app: rtsp-stream-aisle
    spec:
      initContainers:
        - name: init-samples
          image: alpine
          command:
          - wget 
          - "-O"
          - "/samples/aisle.mp4"
          - https://download.microsoft.com/download/b89058d8-f51e-4cb9-a4e0-ec6a85a39863/supermarket-aisle.mp4
          volumeMounts:
          - name: video-storage
            mountPath: /samples
      containers:
        - name: rtsp-stream
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8554
          env:
          - name: SOURCE_URL
            value: "file:///samples/aisle.mp4"
          volumeMounts:
          - mountPath: /samples
            name: video-storage
      volumes: 
      - name: video-storage
        persistentVolumeClaim:
          claimName: video-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-stream-zoom
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rtsp-stream-zoom
  template:
    metadata:
      labels:
        app: rtsp-stream-zoom
    spec:
      initContainers:
        - name: init-samples
          image: mcr.microsoft.com/cbl-mariner/base/core:2.0
          command: 
          - sh
          - -c
          - |
            tdnf update -y
            tdnf install wget -y
            wget -O /samples/zoom.mp4 https://download.microsoft.com/download/b89058d8-f51e-4cb9-a4e0-ec6a85a39863/supermarket-zoom.mp4 --no-check-certificate
          volumeMounts:
          - name: video-storage
            mountPath: /samples
      containers:
      - name: rtsp-stream-zoom
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8554
        env:
        - name: SOURCE_URL
          value: "file:///samples/zoom.mp4"
        volumeMounts:
        - mountPath: /samples
          name: video-storage
      volumes:
      - name: video-storage
        persistentVolumeClaim:
          claimName: video-storage
