apiVersion: v1
kind: Service
metadata:
  name: rtsp-stream
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: rtsp
  selector:
    app: rtsp-stream
