apiVersion: v1
data:
  azure-eventhub-connection-string: ""
kind: Secret
metadata:
  creationTimestamp: "2024-11-11T19:04:01Z"
  name: azure-eventhub-secret
  namespace: contoso-hypermarket
  resourceVersion: "33965"
  uid: dc8eac06-9515-4553-a4b2-fe5ee2bcae7c
type: Opaque