services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA="Y"
      - MSSQL_SA_PASSWORD=ArcPassword123!!
    restart: always

  mssql-setup-job:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssql_setup_job
    command: ["/bin/bash", "-c", "sleep 5s && /tmp/sql-setup.sh"]
    restart : "no"
    environment:
      - MSSQL_SA_PASSWORD=ArcPassword123!!
    volumes:
      - mssql-data:/var/opt/mssql
      - ./cerebral_api/operations/sql-setup.sh:/tmp/sql-setup.sh
    depends_on:
      mssql:
        condition: service_started

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "9999:9999"
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    deploy:
    restart: always

  influxdb-setup-job:
    image: influxdb:latest
    container_name: influxdb_setup_job
    volumes:
      - ./cerebral_api/operations/influxdb-setup.sh:/docker-entrypoint-initdb.d/influxdb-setup.sh  # Mount the setup script
    command: ["/bin/bash", "/docker-entrypoint-initdb.d/influxdb-setup.sh"]  # Run the script
    depends_on:
      - influxdb
    restart: "no"

  rag-on-edge-simulator:
    image: agoraarmbladev.azurecr.io/rag-on-edge-simulator:1.2  # Docker image
    container_name: rag_on_edge_simulator  # Name of the container
    ports:
      - "5000:5000"  # Expose container port 5000
    environment:
      INFLUXDB_URL: "http://influxdb:8086"  # Environment variables
      INFLUXDB_TOKEN: "secret-token"
      INFLUXDB_ORG: "InfluxData"
      INFLUXDB_BUCKET: "manufacturing"
      VERBOSE: "true"
    restart: always  # Optional: Restart policy

  cerebral-api:
    build:
        context: ./cerebral_api/src  # This should point to the folder containing the Dockerfile and requirements.txt
        dockerfile: Dockerfile
    container_name: cerebral_api  # Name of the container
    ports:
      - "5004:5004"  # Map host port 5003 to container port 5003
      - "8000:8000"  # Map host port 8000 to container port 8000
    environment:
      AZURE_OPENAI_API_KEY: "1e70e000ac4c44548f055131cec42f5d"  # Environment variables
      CHATGPT_MODEL: "gpt-35-turbo"
      AZURE_OPENAI_ENDPOINT: "https://armbla-openai.openai.azure.com/"
      OPENAI_API_VERSION: "2024-03-01-preview"
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_BUCKET: "manufacturing"
      INFLUXDB_TOKEN: "secret-token"
      INFLUXDB_ORG: "InfluxData"
    restart: always  # Optional: Restart policy


volumes:
  mssql-data:
    driver: local
  influxdb-storage:
    driver: local