services:
  footfall_ai_api:
    build:
      context: ./footfall_ai_api/src  # This should point to the folder containing the Dockerfile and requirements.txt
      dockerfile: Dockerfile
    container_name: footfall_ai_api_container
    volumes:
      - C:\Users\fcabrera\Downloads\models:/tmp/models
    ports:
      - "5000:5000"  # Adjusting to expose port 80 as mapped in the Dockerfile
    environment:
      - MODEL_PATH=/tmp/models/yolov8n.pt
      - RTSP_URL=rtsp://rtsp_stream_container:8554/stream

  intrusion_detection_api:
    build:
      context: ./intrusion_detection_api/src  # This should point to the folder containing the Dockerfile and requirements.txt
      dockerfile: Dockerfile
    container_name: intrusion_detection_api_container
    volumes:
      - C:\Users\fcabrera\Downloads\models:/tmp/models
    ports:
      - "5001:5001"  # Adjusting to expose port 80 as mapped in the Dockerfile
    environment:
      - MODEL_PATH=/tmp/models/
      - RTSP_URL=rtsp://rtsp_stream_container:8554/stream
      - FLASK_PORT=5001

  rtsp_stream:
    image: kerberos/virtual-rtsp:1.0.6
    container_name: rtsp_stream_container
    ports:
      - "554:8554"
    volumes:
      - C:\Users\fcabrera\Downloads\samples:/samples
    environment:
      - SOURCE_URL=file:///samples/sample.mp4
    restart: always
