apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: contoso-hypermarket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: footfall-ai-api
  namespace: contoso-hypermarket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: footfall-ai-api
  template:
    metadata:
      labels:
        app: footfall-ai-api
    spec:
      initContainers:
      - name: init-download-model
        image: mcr.microsoft.com/onebranch/cbl-mariner/build:2.0
        command: ['sh', '-c', 'wget -O /tmp/models/yolov8n.pt https://huggingface.co/Ultralytics/YOLOv8/resolve/main/yolov8n.pt']
        volumeMounts:
        - name: models-volume
          mountPath: /tmp/models
      containers:
      - name: footfall-ai-api
        image: agacr6b99f.azurecr.io/footfall-ai-api:latest
        ports:
        - containerPort: 5003
        env:
        - name: MODEL_PATH
          value: "/tmp/models/yolov8n.pt"
        - name: RTSP_URL
          value: "rtsp://rtsp-stream:8554/stream"
        volumeMounts:
        - mountPath: /tmp/models
          name: models-volume
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: model-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: footfall-ai-api
  namespace: contoso-hypermarket
spec:
  selector:
    app: footfall-ai-api
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: LoadBalancer
